### PR TITLE
Multiple sort update

### PR DESCRIPTION
**Pull request by AntonPolyakin**
Added multiple field sorting

[[中文版模板 / Chinese template](https://github.com/VisActor/VTable/blob/main/.github/PULL_REQUEST_TEMPLATE/pr_cn.md?plain=1)]

### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [x] Enhancement feature
- [ ] Refactoring
- [ ] Update dependency
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Site / documentation update
- [x] Demo update
- [ ] Workflow
- [ ] Chore
- [ ] Release
- [ ] Other (about what?)

### 🔗 Related issue link

https://github.com/VisActor/VTable/issues/1265
https://github.com/VisActor/VTable/issues/1076

### 💡 Background and solution

Added multiple field sorting. A new property of options “multipleSort: boolean” was added for its use

### 📝 Changelog

The function has not been tested with other functions, such as drag and drop columns, etc. 

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

---

### 🚀 Summary

copilot:summary

### 🔍 Walkthrough

copilot:walkthrough

### CODE REVIEW

**Comment by AntonPolyakin** [comment]
No need to add my version of sort.ts file, better to keep your current version

**Comment by fangsmile** [comment]
> No need to add my example of sort.ts file, it is better to leave your current version

I'm not sure I know what you mean

@AntonPolyakin

**Comment by fangsmile** [comment]
@AntonPolyakin 
Demo for this function and options and tutorial need to be completed！ In folder 
image

and preview it:
image

**Comment by fangsmile** [comment]
#1265  #1076 You can refer to the previous user needs, whether your logic meets

**Comment by AntonPolyakin** [comment]
I will add everything necessary to the documentation

**Comment by AntonPolyakin** [comment]
Fixed some bugs from the previous commit and added documentation for the new `multipleSort` property  to /vtable/guide/basic_function/sort/list_sort (Multiple column sorting)

**Comment by fangsmile** [comment]
In addition, you need to ensure that these two methods are executed correctly。And no breakchanges，or has done compatibility?  @AntonPolyakin 

image

**Comment by AntonPolyakin** [comment]
I tested updateSortState and it does the sorting correctly, but it doesn't set the sort icons correctly. This function was broken before me, but I will fix it and make a new commit.
I tried to ensure full compatibility. Soon I will use this version in a real project and I will have more opportunities to test the sorting together with other VTable features

**Comment by fangsmile** [comment]
OK, i will merge it into develop branch.

In addition, you can build it in your local project firstly!
Put the build package into your business project.


> I tested updateSortState and it does the sorting correctly, but it doesn't set the sort icons correctly. This function was broken before me, but I will fix it and make a new commit. I tried to ensure full compatibility. Soon I will use this version in a real project and I will have more opportunities to test the sorting together with other VTable features

**Comment by fangsmile** [comment]
Please check： https://github.com/VisActor/VTable/pull/2316

some problems should be fixed @AntonPolyakin

**Comment by AntonPolyakin** [comment]
Thanks, I'll test these cases and fix them

**Comment by xuanhun** [comment]
https://juejin.cn/spost/7427836936117010483 请加飞书群，领取奖品

**Pull request merged**
